"""create verticles table

Revision ID: 2a612b23eeec
Revises: 3fc834ed9745
Create Date: 2025-06-08 20:33:19.639123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a612b23eeec'
down_revision: Union[str, None] = '3fc834ed9745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verticles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verticles_id'), 'verticles', ['id'], unique=False)
    op.create_index(op.f('ix_verticles_name'), 'verticles', ['name'], unique=True)
    op.create_index(op.f('ix_products_verticle'), 'products', ['verticle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_verticle'), table_name='products')
    op.drop_index(op.f('ix_verticles_name'), table_name='verticles')
    op.drop_index(op.f('ix_verticles_id'), table_name='verticles')
    op.drop_table('verticles')
    # ### end Alembic commands ###
